### ISSUE TITLE
Android 11渲染失败，返回-1001错误

### ISSUE THREAD

**Issue by lxj-helloworld** [kuaifan/eeui-template#18]
E/weex: onRenderError -1001,degradeToH5|createInstance fail|wx_create_instance_error isJSFrameworkInit==false reInitCount == 1

![WechatIMG55](https://user-images.githubusercontent.com/31557081/99891213-7ee20d80-2ca2-11eb-83bd-9544d422c5a1.jpeg)

**Comment by kuaifan** [comment]
新版本已经修复
